[metadata]
name = CyberTrap-AI
version = 1.0.0
author = Security Team
description = Honeypot-Based Attack Intelligence and Threat Analysis Platform
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/luciferxeditor728-dot/CyberTrape-AI
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11

[options]
zip_safe = False
include_package_data = True
packages = find:
python_requires = >=3.9

[options.packages.find]
where = .
exclude =
    tests*
    docs*
